name: city_go
description: CityGo Yaroslavl app
version: 0.0.0+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI section
  cupertino_icons: ^1.0.3
  provider: ^5.0.0
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  webview_flutter: ^2.0.10
  auto_size_text: ^3.0.0-nullsafety.0
  flare_flutter: ^3.0.2
  sliding_up_panel: ^2.0.0+1

  # Logic section
  flutter_bloc: ^7.1.0
  hive: ^2.0.4
  equatable: ^2.0.3
  rxdart: ^0.27.1
  get_it: ^7.2.0
  mockito: ^5.0.7
  package_info: ^2.0.2
  device_info: ^2.0.2
  connectivity: ^3.0.6
  dio: ^4.0.0
  permission_handler: ^7.1.0
  geolocator: ^7.4.0
  path_provider: ^2.0.2
  just_audio: ^0.9.5
  audio_service: ^0.17.1
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2

flutter:
  uses-material-design: true
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/jost/TrueType/Jost-100-Hairline.ttf
        - asset: assets/fonts/jost/TrueType/Jost-100-HairlineItalic.ttf
        - asset: assets/fonts/jost/TrueType/Jost-200-Thin.ttf
        - asset: assets/fonts/jost/TrueType/Jost-200-ThinItalic.ttf
        - asset: assets/fonts/jost/TrueType/Jost-400-Book.ttf
        - asset: assets/fonts/jost/TrueType/Jost-400-BookItalic.ttf
        - asset: assets/fonts/jost/TrueType/Jost-600-Semi.ttf
        - asset: assets/fonts/jost/TrueType/Jost-600-SemiItalic.ttf
        - asset: assets/fonts/jost/TrueType/Jost-800-Heavy.ttf
        - asset: assets/fonts/jost/TrueType/Jost-800-HeavyItalic.ttf
        - asset: assets/fonts/jost/TrueType/Jost-900-Black.ttf
        - asset: assets/fonts/jost/TrueType/Jost-900-BlackItalic.ttf
          style: italic
    - family: MontserRat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
          style: italic
    - family: AleGrey
      fonts:
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-Black.ttf
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-BlackItalic.ttf
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-Bold.ttf
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-BoldItalic.ttf
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-Light.ttf
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-LightItalic.ttf
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-Medium.ttf
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-MediumItalic.ttf
          style: italic
  assets:
    - assets/localization/
    - assets/images/
    - assets/images/points/
    - assets/flare/