name: city_go
description: CityGo Yaroslavl app
version: 0.0.0+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI section
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  google_maps_flutter: ^0.5.31
  flutter_polyline_points: ^0.2.3

  # Logic section
  bloc: ^6.0.3
  hive: ^1.4.4
  equatable: ^1.2.5
  rxdart: ^0.24.1
  get_it: ^4.0.4
  mockito: ^4.1.1
  package_info: ^0.4.3
  device_info: ^0.4.2+7
  connectivity: ^0.4.9+2
  dio: ^3.0.10
  dio_flutter_transformer: ^3.0.2
  permission_handler: ^5.0.1+1
  geolocator: ^6.0.0+4
  path_provider: ^1.6.14
  just_audio: ^0.4.4
  audio_service: ^0.15.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/localization/