name: city_go
description: CityGo Yaroslavl app
version: 0.0.0+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI section
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  google_maps_flutter: ^2.0.1
  flutter_polyline_points: ^0.2.4
  flutter_webview_plugin: ^0.3.11
  auto_size_text: ^2.1.0
  flare_flutter: ^2.0.6
  sliding_up_panel: ^1.0.2

  # Logic section
  bloc: ^7.0.0-nullsafety.3
  hive: ^2.0.0
  equatable: ^2.0.0
  rxdart: ^0.26.0
  get_it: ^6.0.0
  mockito: ^5.0.0
  package_info: ^2.0.0
  device_info: ^2.0.0
  connectivity: ^3.0.2
  dio: ^4.0.0-beta6
  permission_handler: ^6.0.1
  geolocator: ^7.0.1
  path_provider: ^2.0.1
  just_audio: ^0.7.0
  audio_service: ^0.17.0-nullsafety.0
  url_launcher: ^6.0.2

dependency_overrides:
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5

flutter:
  uses-material-design: true
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/jost/TrueType/Jost-100-Hairline.ttf
        - asset: assets/fonts/jost/TrueType/Jost-100-HairlineItalic.ttf
        - asset: assets/fonts/jost/TrueType/Jost-200-Thin.ttf
        - asset: assets/fonts/jost/TrueType/Jost-200-ThinItalic.ttf
        - asset: assets/fonts/jost/TrueType/Jost-400-Book.ttf
        - asset: assets/fonts/jost/TrueType/Jost-400-BookItalic.ttf
        - asset: assets/fonts/jost/TrueType/Jost-600-Semi.ttf
        - asset: assets/fonts/jost/TrueType/Jost-600-SemiItalic.ttf
        - asset: assets/fonts/jost/TrueType/Jost-800-Heavy.ttf
        - asset: assets/fonts/jost/TrueType/Jost-800-HeavyItalic.ttf
        - asset: assets/fonts/jost/TrueType/Jost-900-Black.ttf
        - asset: assets/fonts/jost/TrueType/Jost-900-BlackItalic.ttf
          style: italic
    - family: MontserRat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
          style: italic
    - family: AleGrey
      fonts:
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-Black.ttf
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-BlackItalic.ttf
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-Bold.ttf
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-BoldItalic.ttf
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-Light.ttf
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-LightItalic.ttf
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-Medium.ttf
        - asset: assets/fonts/alegreyasanssc/AlegreyaSansSC-MediumItalic.ttf
          style: italic
  assets:
    - assets/localization/
    - assets/images/
    - assets/images/points/
    - assets/flare/